
# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         python-version: 3.9
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Install dependencies  # Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/house_pricing/requirements.txt
      - name: Run build  # Run tests using pytest
        run: python src/house_pricing/main.py
        
