name: CI/CD Pipeline  # Name of the GitHub Actions workflow

on:
  push:
    branches: [master]  # Trigger the workflow on push to the 'master' branch

env:
  IMAGE_NAME: kuyu12/mymodel  # Define an environment variable for the Docker image name

jobs:

  test:  # Job to run tests
    runs-on: ubuntu-latest  # Run this job on the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v3  # Check out the repository code
    - name: Set up Python  # Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Specify Python version 3.9
    - name: Install dependencies  # Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/house_pricing/requirements.txt
    - name: Run tests  # Run tests using pytest
      run: |
        python  src/house_pricing/main.py
