
# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         python-version: 3.9
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Install dependencies  # Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/house_pricing/requirements.txt
      - name: Run build  # Run tests using pytest
        run: python src/house_pricing/main.py
      - name: Add .pkl file to git
        run: |
          git config --global user.name "Your GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/house_pricing/classification.pkl
          git commit -m "Add updated classification.pkl"
          git push origin develop  # Push to the develop branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
