
# This is a basic workflow to help you get started with Actions

name: CI/CD Pipeline

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
permissions:
  contents: write 
  packages: write
env:
  IMAGE_NAME: miriezrubelsky/house-pricing-app  # Define an environment variable for the Docker image name  
jobs:
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         python-version: 3.9
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Install dependencies  # Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/house_pricing/requirements.txt
      - name: Run build  
        run: python src/house_pricing/main.py
      - name: Add .pkl file to git
        run: |
          git config --global user.name "Your GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/house_pricing/trained_model/classification.pkl
          git commit -m "Add updated classification.pkl"
          git push origin develop  # Push to the develop branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Set up Docker Buildx  # Set up Docker Buildx for building images
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry  # Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # GitHub Container Registry URL
          username: ${{ github.actor }}  # Use the GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}  # Use a GitHub token from secrets
      - name: Build and push Docker image  # Build and push the Docker image
        run: |
          docker build -t ghcr.io/${{ env.IMAGE_NAME }}:latest .  # Build the Docker image
          docker push ghcr.io/${{ env.IMAGE_NAME }}:latest  # Push the Docker image to GitHub Container Registry
